spring:
  h2:
    console:
      enabled: true
  cloud:
    config:
      url: "http://localhost:8888"
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"
server:
  port: 8086



products:
  exclusives:
  - "Assistance"
  - "24hService"

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "refresh"]